version: '3.8' 

services:
  arb:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 src/main.py  
    restart: always  
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - REDIS_HOST=redis
    volumes:
      - ./logs/:/app/logs


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: